import { useState, useEffect, useRef } from "react";
import { useQuery, useMutation } from "convex/react";
import { api } from "@story-telling-v2/backend/convex/_generated/api";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
	Dialog,
	DialogContent,
	DialogDescription,
	DialogFooter,
	DialogHeader,
	DialogTitle,
} from "@/components/ui/dialog";
import { Badge } from "@/components/ui/badge";
import { Plus, Edit2, Trash2, Save, X, FileText, Calendar, User } from "lucide-react";
import { toast } from "sonner";
import type { Id } from "@story-telling-v2/backend/convex/_generated/dataModel";
import EditorJS from "@editorjs/editorjs";
import Header from "@editorjs/header";
import List from "@editorjs/list";
import Paragraph from "@editorjs/paragraph";
import Quote from "@editorjs/quote";
import Code from "@editorjs/code";
// @ts-ignore - No type definitions available
import LinkTool from "@editorjs/link";
// @ts-ignore - No type definitions available
import Image from "@editorjs/simple-image";
import Table from "@editorjs/table";
import Warning from "@editorjs/warning";
import Delimiter from "@editorjs/delimiter";
import InlineCode from "@editorjs/inline-code";
// @ts-ignore - No type definitions available
import Marker from "@editorjs/marker";
// @ts-ignore - No type definitions available
import Checklist from "@editorjs/checklist";

interface Blog {
	_id: Id<"blogs">;
	title: string;
	slug: string;
	content: any;
	excerpt?: string;
	status: "draft" | "published";
	publishedAt?: number;
	createdAt: number;
	updatedAt: number;
}

export function AdminBlog() {
	// @ts-ignore - API types will be regenerated by Convex after blogs.ts is deployed
	const blogs = useQuery(api.blogs.listAll);
	// @ts-ignore - API types will be regenerated by Convex after blogs.ts is deployed
	const createBlog = useMutation(api.blogs.create);
	// @ts-ignore - API types will be regenerated by Convex after blogs.ts is deployed
	const updateBlog = useMutation(api.blogs.update);
	// @ts-ignore - API types will be regenerated by Convex after blogs.ts is deployed
	const deleteBlog = useMutation(api.blogs.remove);

	const [isDialogOpen, setIsDialogOpen] = useState(false);
	const [editingBlog, setEditingBlog] = useState<Blog | null>(null);
	const [title, setTitle] = useState("");
	const [slug, setSlug] = useState("");
	const [excerpt, setExcerpt] = useState("");
	const [status, setStatus] = useState<"draft" | "published">("draft");
	const [editorInstance, setEditorInstance] = useState<EditorJS | null>(null);
	const [isEditorReady, setIsEditorReady] = useState(false);
	const editorRef = useRef<HTMLDivElement>(null);
	const editorInstanceRef = useRef<EditorJS | null>(null);

	// Initialize Editor.js
	useEffect(() => {
		if (!isDialogOpen) {
			return;
		}

		// Reset editor ready state when dialog opens
		setIsEditorReady(false);

		// Destroy existing instance if any
		if (editorInstanceRef.current) {
			try {
				editorInstanceRef.current.destroy();
			} catch (err) {
				console.error("Error destroying editor:", err);
			}
			editorInstanceRef.current = null;
			setEditorInstance(null);
		}

		// Wait for the DOM element to be available
		const initEditor = async () => {
			// Small delay to ensure DOM is ready
			await new Promise((resolve) => setTimeout(resolve, 100));

			if (!editorRef.current) {
				console.error("Editor ref is not available");
				return;
			}

			try {
				const editor = new EditorJS({
					holder: editorRef.current,
					tools: {
						header: {
							class: Header,
							config: {
								levels: [1, 2, 3, 4, 5, 6],
								defaultLevel: 2,
							},
						} as any,
						list: {
							class: List,
							inlineToolbar: true,
						} as any,
						paragraph: {
							class: Paragraph,
							inlineToolbar: true,
						} as any,
						quote: {
							class: Quote,
							inlineToolbar: true,
						} as any,
						code: Code as any,
						linkTool: LinkTool as any,
						image: Image as any,
						table: {
							class: Table,
							inlineToolbar: true,
						} as any,
						warning: Warning as any,
						delimiter: Delimiter as any,
						inlineCode: InlineCode as any,
						marker: Marker as any,
						checklist: {
							class: Checklist,
							inlineToolbar: true,
						} as any,
					},
					data: editingBlog?.content || {
						blocks: [
							{
								type: "paragraph",
								data: {
									text: "",
								},
							},
						],
					},
				});

				await editor.isReady;
				editorInstanceRef.current = editor;
				setEditorInstance(editor);
				setIsEditorReady(true);
			} catch (err) {
				console.error("Editor.js initialization error:", err);
				toast.error("Failed to initialize editor");
				setIsEditorReady(false);
			}
		};

		initEditor();

		return () => {
			if (editorInstanceRef.current) {
				try {
					editorInstanceRef.current.destroy();
				} catch (err) {
					console.error("Error destroying editor:", err);
				}
				editorInstanceRef.current = null;
				setEditorInstance(null);
			}
			setIsEditorReady(false);
		};
	}, [isDialogOpen, editingBlog?._id]);

	// Generate slug from title
	const generateSlug = (text: string) => {
		return text
			.toLowerCase()
			.trim()
			.replace(/[^\w\s-]/g, "")
			.replace(/[\s_-]+/g, "-")
			.replace(/^-+|-+$/g, "");
	};

	const handleTitleChange = (value: string) => {
		setTitle(value);
		if (!editingBlog) {
			setSlug(generateSlug(value));
		}
	};

	const handleOpenDialog = (blog?: Blog) => {
		if (blog) {
			setEditingBlog(blog);
			setTitle(blog.title);
			setSlug(blog.slug);
			setExcerpt(blog.excerpt || "");
			setStatus(blog.status);
		} else {
			setEditingBlog(null);
			setTitle("");
			setSlug("");
			setExcerpt("");
			setStatus("draft");
		}
		setIsDialogOpen(true);
	};

	const handleCloseDialog = () => {
		setIsDialogOpen(false);
		setEditingBlog(null);
		setTitle("");
		setSlug("");
		setExcerpt("");
		setStatus("draft");
		setIsEditorReady(false);
		if (editorInstanceRef.current) {
			try {
				editorInstanceRef.current.destroy();
			} catch (err) {
				console.error("Error destroying editor:", err);
			}
			editorInstanceRef.current = null;
			setEditorInstance(null);
		}
	};

	const handleSave = async () => {
		if (!title.trim() || !slug.trim()) {
			toast.error("Title and slug are required");
			return;
		}

		if (!editorInstance || !isEditorReady) {
			toast.error("Editor is not ready. Please wait a moment and try again.");
			return;
		}

		try {
			const outputData = await editorInstance.save();

			if (editingBlog) {
				await updateBlog({
					blogId: editingBlog._id,
					title: title.trim(),
					slug: slug.trim(),
					content: outputData,
					excerpt: excerpt.trim() || undefined,
					status,
				});
				toast.success("Blog updated successfully");
			} else {
				await createBlog({
					title: title.trim(),
					slug: slug.trim(),
					content: outputData,
					excerpt: excerpt.trim() || undefined,
					status,
				});
				toast.success("Blog created successfully");
			}

			handleCloseDialog();
		} catch (error: any) {
			console.error("Error saving blog:", error);
			toast.error(error.message || "Failed to save blog");
		}
	};

	const handleDelete = async (blog: Blog) => {
		if (!confirm(`Are you sure you want to delete "${blog.title}"?`)) return;

		try {
			await deleteBlog({ blogId: blog._id });
			toast.success("Blog deleted successfully");
		} catch (error: any) {
			toast.error(error.message || "Failed to delete blog");
		}
	};

	if (blogs === undefined) {
		return (
			<div className="flex items-center justify-center py-20">
				<div className="animate-spin rounded-full h-8 w-8 border-b-2 border-primary"></div>
			</div>
		);
	}

	return (
		<div className="space-y-4">
			<div className="flex items-center justify-between">
				<div>
					<h2 className="text-2xl font-bold">Blog Posts</h2>
					<p className="text-muted-foreground">Manage your blog content</p>
				</div>
				<Button onClick={() => handleOpenDialog()}>
					<Plus className="h-4 w-4 mr-2" />
					New Blog Post
				</Button>
			</div>

			{blogs.length === 0 ? (
				<Card>
					<CardContent className="flex flex-col items-center justify-center py-12">
						<FileText className="h-12 w-12 text-muted-foreground mb-4" />
						<p className="text-muted-foreground mb-4">No blog posts yet</p>
						<Button onClick={() => handleOpenDialog()}>
							<Plus className="h-4 w-4 mr-2" />
							Create Your First Blog Post
						</Button>
					</CardContent>
				</Card>
			) : (
				<div className="grid gap-4">
					{blogs.map((blog: Blog) => (
						<Card key={blog._id}>
							<CardHeader>
								<div className="flex items-start justify-between">
									<div className="flex-1">
										<CardTitle className="flex items-center gap-2 mb-2">
											{blog.title}
											<Badge variant={blog.status === "published" ? "default" : "secondary"}>
												{blog.status}
											</Badge>
										</CardTitle>
										<CardDescription className="flex items-center gap-4 mt-2">
											<span className="flex items-center gap-1">
												<Calendar className="h-3 w-3" />
												{new Date(blog.createdAt).toLocaleDateString()}
											</span>
											{blog.publishedAt && (
												<span className="flex items-center gap-1">
													Published: {new Date(blog.publishedAt).toLocaleDateString()}
												</span>
											)}
										</CardDescription>
										{blog.excerpt && (
											<p className="text-sm text-muted-foreground mt-2">{blog.excerpt}</p>
										)}
									</div>
									<div className="flex items-center gap-2">
										<Button
											variant="outline"
											size="sm"
											onClick={() => handleOpenDialog(blog)}
										>
											<Edit2 className="h-4 w-4" />
										</Button>
										<Button
											variant="outline"
											size="sm"
											onClick={() => handleDelete(blog)}
										>
											<Trash2 className="h-4 w-4" />
										</Button>
									</div>
								</div>
							</CardHeader>
						</Card>
					))}
				</div>
			)}

			<Dialog open={isDialogOpen} onOpenChange={setIsDialogOpen}>
				<DialogContent className="max-w-4xl max-h-[90vh] overflow-y-auto">
					<DialogHeader>
						<DialogTitle>{editingBlog ? "Edit Blog Post" : "Create Blog Post"}</DialogTitle>
						<DialogDescription>
							{editingBlog ? "Update your blog post content" : "Create a new blog post"}
						</DialogDescription>
					</DialogHeader>

					<div className="space-y-4 py-4">
						<div className="space-y-2">
							<Label htmlFor="title">Title *</Label>
							<Input
								id="title"
								value={title}
								onChange={(e) => handleTitleChange(e.target.value)}
								placeholder="Enter blog post title"
							/>
						</div>

						<div className="space-y-2">
							<Label htmlFor="slug">Slug *</Label>
							<Input
								id="slug"
								value={slug}
								onChange={(e) => setSlug(e.target.value)}
								placeholder="blog-post-slug"
							/>
						</div>

						<div className="space-y-2">
							<Label htmlFor="excerpt">Excerpt</Label>
							<Input
								id="excerpt"
								value={excerpt}
								onChange={(e) => setExcerpt(e.target.value)}
								placeholder="Brief description of the blog post"
							/>
						</div>

						<div className="space-y-2">
							<Label htmlFor="status">Status</Label>
							<select
								id="status"
								value={status}
								onChange={(e) => setStatus(e.target.value as "draft" | "published")}
								className="flex h-10 w-full rounded-md border border-input bg-background px-3 py-2 text-sm ring-offset-background file:border-0 file:bg-transparent file:text-sm file:font-medium placeholder:text-muted-foreground focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:cursor-not-allowed disabled:opacity-50"
							>
								<option value="draft">Draft</option>
								<option value="published">Published</option>
							</select>
						</div>

						<div className="space-y-2">
							<Label>Content *</Label>
							{!isEditorReady && (
								<div className="text-sm text-muted-foreground mb-2">
									Initializing editor...
								</div>
							)}
							<div
								ref={editorRef}
								className="min-h-[400px] border rounded-md p-4 bg-background"
							/>
						</div>
					</div>

					<DialogFooter>
						<Button variant="outline" onClick={handleCloseDialog}>
							<X className="h-4 w-4 mr-2" />
							Cancel
						</Button>
						<Button onClick={handleSave} disabled={!isEditorReady}>
							<Save className="h-4 w-4 mr-2" />
							{editingBlog ? "Update" : "Create"}
						</Button>
					</DialogFooter>
				</DialogContent>
			</Dialog>
		</div>
	);
}
