import type { NextConfig } from "next";

// Auth requests are proxied through src/app/api/auth/[...path]/route.ts
// so Better Auth's trustedOrigins check receives a known-good Origin header.
const nextConfig: NextConfig = {
  // 301 redirect non-www → www so Google sees one canonical host.
  // Without this, lallifafa.com and www.lallifafa.com are treated as
  // duplicate content and Google may pick the wrong canonical.
  async redirects() {
    return [
      {
        source: "/:path*",
        has: [{ type: "host", value: "lallifafa.com" }],
        destination: "https://www.lallifafa.com/:path*",
        permanent: true,
      },
    ];
  },
  images: {
    remotePatterns: [
      // Convex storage (scene images generated by AI)
      {
        protocol: "https",
        hostname: "*.convex.cloud",
      },
      // Convex site HTTP actions (fallback)
      {
        protocol: "https",
        hostname: "*.convex.site",
      },
    ],
  },
};

export default nextConfig;
