import type { NextConfig } from "next";

// Auth requests are proxied through src/app/api/auth/[...path]/route.ts
// so Better Auth's trustedOrigins check receives a known-good Origin header.
const nextConfig: NextConfig = {
  async redirects() {
    return [
      {
        source: "/:path*",
        has: [{ type: "host", value: "lallifafa.com" }],
        destination: "https://www.lallifafa.com/:path*",
        permanent: true,
      },
    ];
  },

  async headers() {
    return [
      {
        source: "/(.*)",
        headers: [
          { key: "X-Content-Type-Options", value: "nosniff" },
          { key: "X-Frame-Options", value: "SAMEORIGIN" },
          { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
          {
            key: "Permissions-Policy",
            value: "camera=(), microphone=(), geolocation=(), interest-cohort=()",
          },
          {
            key: "Content-Security-Policy",
            value: [
              "default-src 'self'",
              // GA4 + Google Ads (AW-*) + Meta Pixel scripts
              "script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://googleads.g.doubleclick.net https://pagead2.googlesyndication.com https://www.googleadservices.com https://connect.facebook.net https://challenges.cloudflare.com",
              "style-src 'self' 'unsafe-inline' https://fonts.googleapis.com",
              "font-src 'self' https://fonts.gstatic.com",
              // Meta Pixel noscript 1×1 + Google Ads measurement + remarketing pixels
              "img-src 'self' data: blob: https://*.convex.cloud https://*.convex.site https://www.google-analytics.com https://www.googletagmanager.com https://www.google.com https://www.google.co.in https://www.facebook.com https://googleads.g.doubleclick.net https://ad.doubleclick.net https://www.googleadservices.com",
              // GA4 regional endpoints + Google Ads conversion + remarketing + Meta Pixel beacon
              "connect-src 'self' https://*.convex.cloud https://*.convex.site https://www.google-analytics.com https://analytics.google.com https://region1.google-analytics.com https://www.googletagmanager.com https://www.google.com https://stats.g.doubleclick.net https://googleads.g.doubleclick.net https://ad.doubleclick.net https://www.googleadservices.com https://www.facebook.com https://connect.facebook.net https://api.razorpay.com wss://*.convex.cloud",
              "media-src 'self' blob: https://*.convex.cloud https://*.convex.site",
              "frame-src https://api.razorpay.com https://bid.g.doubleclick.net https://challenges.cloudflare.com",
              "object-src 'none'",
              "base-uri 'self'",
              "form-action 'self'",
            ].join("; "),
          },
        ],
      },
    ];
  },
  images: {
    remotePatterns: [
      // Convex storage (scene images generated by AI)
      {
        protocol: "https",
        hostname: "*.convex.cloud",
      },
      // Convex site HTTP actions (fallback)
      {
        protocol: "https",
        hostname: "*.convex.site",
      },
    ],
  },
};

export default nextConfig;
